# Generated by Django 4.1.4 on 2022-12-19 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "item_description",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("quantity", models.IntegerField(blank=True, default="0", null=True)),
                (
                    "purchased_quantity",
                    models.IntegerField(blank=True, default="0", null=True),
                ),
                (
                    "purchased_by",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "sale_quantity",
                    models.IntegerField(blank=True, default="0", null=True),
                ),
                ("sale_by", models.CharField(blank=True, max_length=50, null=True)),
                ("sale_to", models.CharField(blank=True, max_length=50, null=True)),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_by", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "reorder_level",
                    models.IntegerField(blank=True, default="0", null=True),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("export_to_CSV", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.category",
                    ),
                ),
            ],
        ),
    ]
