# Generated by Django 4.1.4 on 2022-12-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="item_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
