# Generated by Django 4.1.4 on 2022-12-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_stock_expiry"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stock",
            old_name="purchase_price",
            new_name="unit_purchase_price",
        ),
        migrations.RenameField(
            model_name="stock",
            old_name="sale_price",
            new_name="unit_sale_price",
        ),
    ]
