# Generated by Django 4.1.4 on 2022-12-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_cash"),
    ]

    operations = [
        migrations.AddField(
            model_name="cash",
            name="export_to_CSV",
            field=models.BooleanField(default=False),
        ),
    ]
