# Generated by Django 4.1.4 on 2022-12-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_cash_export_to_csv"),
    ]

    operations = [
        migrations.AddField(
            model_name="cash",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
