# Generated by Django 4.1.4 on 2022-12-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_cash_amount_in_alter_cash_amount_out_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cash",
            name="issue_by",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
