# Generated by Django 4.1.4 on 2022-12-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_cash_issue_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="cash",
            name="impriest_level",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
