# Generated by Django 4.1.4 on 2022-12-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_cashcategory_cash_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cash",
            old_name="balance",
            new_name="bank_balance",
        ),
        migrations.AddField(
            model_name="cash",
            name="cash_balance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
