# Generated by Django 4.1.4 on 2022-12-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_rename_balance_cash_bank_balance_cash_cash_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cash",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[("Bank", "Bank"), ("Cash", "Cash")],
                max_length=50,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="CashCategory",
        ),
    ]
