# Generated by Django 4.1.4 on 2022-12-20 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_cash_category_delete_cashcategory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cash",
            old_name="bank_balance",
            new_name="balance",
        ),
        migrations.RemoveField(
            model_name="cash",
            name="cash_balance",
        ),
    ]
